const commons = {
  // Common
  검색하기: 'Search',
  시군구_선택: 'Select Si Gun Gu',
  시도_선택: 'Select Si Do',
  통합검색: 'Integrated Search',
  홈페이지_주소: 'Website URL',
  연락처: 'Contact',
  여행지: 'Tourist Spot',
  로고: 'Logo',
  검색어를_입력하세요: 'Please enter a search term',
  검색: 'Search',
  이미지_업로드: 'Image Upload',
  제목을_입력하세요: 'Please enter a title',
  내용을_입력하세요: 'Please enter content',
  글_번호: 'Post Number',

  // Main Menu
  지역별_축제정보: 'Festival Information by Region',
  농촌체험_예약: 'Rural Experience Reservation',
  나의_예약현황: 'My Reservation Status',
  조이팜의_추천: 'JOYFARM’s Recommendation',
  지역별_축제_정보: 'Festival Information by Region',
  내_위치_주변_여행지: 'Tourist Spots Around My Location',
  주변_여행지_리스트: 'Nearby Tourist Spots List',
  커뮤니티: 'Community',
  체험_여행후기: 'Experience & Travel Reviews',
  공지사항: 'Notices',
  QnA: 'Q&A',
  공지글로_등록하기: 'Register as Notice',
  사이트_관리: 'Site Management',

  // User
  아이디: 'Username',
  이메일: 'Email',
  인증코드_전송: 'Send Verification Code',
  인증코드_입력: 'Enter Verification Code',
  인증코드: 'Verification Code',
  비밀번호: 'Password',
  비밀번호_확인: 'Confirm Password',
  회원명: 'Member Name',
  휴대전화번호: 'Mobile Phone Number',
  프로필_이미지: 'Profile Image',
  업로드: 'Upload',
  변경하기: 'Change',
  약관에_동의: 'Agree to Terms',
  회원가입_약관에_동의합니다: 'Agree to the Membership Terms',
  확인: 'Confirm',
  재전송: 'Resend',
  다시입력: 'Re-enter',
  가입하기: 'Sign Up',
  확인된_이메일_입니다: 'Email Verified',
  이메일을_입력하세요: 'Please enter your email',
  이메일을_인증하세요: 'Please verify your email',
  인증코드를_입력하세요: 'Please enter the verification code',
  비밀번호를_입력하세요: 'Please enter your password',
  비밀번호가_정확하지_않습니다: 'Password is incorrect',
  비밀번호를_확인하세요: 'Please confirm your password',
  회원명을_입력하세요: 'Please enter your name',
  전화번호를_입력하세요: 'Please enter your phone number',
  회원가입_약관에_동의하세요: 'Please agree to the membership terms',
  회원정보가_수정되었습니다: 'Member information has been updated',
  아직_회원이_아니십니까: 'Not a member yet?',
  ENJOY_YOUR_LIFE_ENJOY_YOUR_FARM: 'ENJOY YOUR LIFE, ENJOY YOUR FARM',
  조이팜과_함께_즐거운_농촌체험: 'Enjoy a fun rural experience with JOYFARM!',
  로그인: 'Login',
  JOYFARM_로그인: 'JOYFARM Login',

  // My Page
  회원정보_수정_중_오류가_발생했습니다:
    'An error occurred while updating member information',
  회원_탈퇴가_완료되었습니다: 'Membership cancellation is complete',
  회원_탈퇴_중_오류가_발생했습니다:
    'An error occurred during membership cancellation',
  회원정보_수정하기: 'Edit Member Information',
  회원정보_수정: 'Edit Member Information',
  회원탈퇴하기: 'Cancel Membership',
  게시글_관리: 'Manage Posts',
  회원정보를_수정하시겠습니까: 'Do you want to edit your member information?',
  회원탈퇴를_진행하시겠습니까:
    'Do you want to proceed with membership cancellation?',
  회원탈퇴완료: 'Membership Cancellation Completed',
  회원탈퇴실패: 'Membership Cancellation Failed',

  // Post
  조회된_게시글이_없습니다: 'No posts found',
  정말_삭제_하겠습니까: 'Are you sure you want to delete?',
  첨부파일_목록: 'Attached Files List',
  댓글_목록: 'Comments List',
  여러분의_소중한_의견을_남겨주세요: 'Please leave your valuable opinion',
  댓글을_입력하세요: 'Please enter a comment',

  // Recommended Tour Places
  추천_여행지: 'Recommended Tour Places',
  추천_여행기간: 'Recommended Travel Period',
  여행지_설명: 'Tour Place Description',
  여행지_찜하기: 'Favorite Tour Place',
  여행코스: 'Travel Course',
  여행장소: 'Travel Location',
  여행지_명: 'Tour Place Name',
  인기_테마: 'Popular #Theme',
  숲체험: '# Forest Experience',
  전통문화: '# Traditional Culture',
  텃밭체험: '# Garden Experience',
  휴양: '# Recreation',
  농촌_관광: '# Rural Tourism',
  힐링: '# Healing',
  테마파크: '# Theme Park',
  캠핑: '# Camping',
  여름휴가: '# Summer Vacation',
  건강: '# Health',
  체험: '# Experience',
  자연휴양림: '# Natural Recreation Forest',

  // Festival
  축제_내용: 'Festival Content',
  행사기간: 'Event Period',
  행사명: 'Event Name',
  행사장소: 'Event Location',
  문의처: 'Contact Information',
  행사내용: 'Event Details',
  길찾기: 'Find Directions',
  주소: 'Address',

  // Experience Reservation
  예약하기: 'Make a Reservation',
  힐링_농촌_체험지: 'Healing Rural Experience Spots',
  농촌체험활동_예약: 'Reserve a Rural Experience Activity',
  체험활동_리스트: 'Experience Activity List',
  체험활동_예약: 'Reserve Experience Activity',
  체험활동_상세_정보: 'Experience Activity Details',
  체험_프로그램_설명: 'Experience Program Description',
  체험_프로그램_소개: 'Introduction to Experience Program',
  보유시설정보: 'Facility Information',
  체험마을_주소: 'Experience Village Address',
  체험마을명: 'Experience Village Name',
  대표전화번호: 'Representative Phone Number',
  예약_확인: 'Confirm Reservation',
  님의_: 'Your',
  체험_활동_소개: 'Experience Activity Introduction',
  체험_마을_대표자명: 'Experience Village Representative Name',
  체험_마을_주소: 'Experience Village Address',
  체험_마을_전화번호: 'Experience Village Phone Number',
  예약일_선택: 'Select Reservation Date',
  예약자_정보_입력: 'Enter Reservation Information',
  예약시간_선택: 'Select Reservation Time',
  인원수_선택: 'Select Number of People',
  체험활동_조회: 'Search Experience Activities',
  예약은_당일로부터_한달_이내만_가능합니다:
    'Reservations are only available within one month from today',

  // Reservation Status
  나의_예약_현황: 'My Reservation Status',
  예약_현황_리스트: 'Reservation Status List',
  예약내역_상세: 'Reservation Details',
  예약_취소: 'Cancel Reservation',
  체험_마을명: 'Experience Village Name',
  예약한_체험_마을_정보: 'Information on Reserved Experience Village',
  예약자_정보: 'Reservation Information',
  예약자명: 'Reservation Name',
  예약자_전화번호: 'Reservation Phone Number',
  예약일: 'Reservation Date',
  예약시간: 'Reservation Time',
  예약인원: 'Number of People',
  예약한_체험_마을: 'Reserved Experience Village',
  체험_마을_세부정보_닫기: 'Close Experience Village Details',
  체험_마을_세부정보_열기: 'Open Experience Village Details',
  조회된_예약_내역이_없습니다: 'No reservation details found',
  농촌체험_예약하기: 'Make a Rural Experience Reservation',

  // My Page
  찜하기_리스트: 'Favorite List',
  조회된_게시물이_없습니다: 'No posts found',
};

export default commons;
