export const color = {
  blue: '#6CC0FF',
  primary: '#007bff',
  secondary: '#6c757d',
  success: '#28a745',
  danger: '#dc3545',
  warning: '#ffc107',
  info: '#17a2b8',
  light: '#E2E2E2',
  dark: '#343a40',
  black: '#000',
  darkGreen: '#428C4C',
  midGreen: '#39AE48',
  lightGreen: '#C2F2B6',
  white: '#ffffff',
  dark_gray: '#333333',
  mid_gray: '#767676',
  line_gray: '#D5D5D5',
  whiteGreen: '#FFFFDE',
  whiteGray: '#cccccc',
  gray: '#ccc',
};

export const buttonColor = {
  primary: [color.primary, '#fff', color.primary],
  secondary: [color.secondary, '#fff', color.secondary],
  success: [color.success, '#fff', color.success],
  danger: [color.danger, '#fff', color.danger],
  warning: [color.warning, '#212529', '#212529'],
  info: [color.info, '#fff', color.info],
  light: [color.light, '#212529', '#212529'],
  dark: [color.dark, '#fff', color.dark],
  darkGreen: [color.darkGreen, '#fff', color.darkGreen],
  midGreen: [color.midGreen, '#fff', color.midGreen],
  lightGreen: [color.lightGreen, '#fff', color.lightGreen],
};
